# Generated by Django 3.2.9 on 2022-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HruModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LULC', models.CharField(max_length=30, verbose_name='土地类别')),
                ('HRU', models.IntegerField(verbose_name='子流域')),
                ('HRUGIS', models.CharField(max_length=50, verbose_name='子流域代号')),
                ('SUB', models.SmallIntegerField(verbose_name='所属的子流域')),
                ('YEAR', models.IntegerField(verbose_name='年份')),
                ('MON', models.IntegerField(verbose_name='月份')),
                ('AREAkm2', models.FloatField(max_length=20, verbose_name='HRU集水面积(km2)')),
                ('PRECIPmm', models.FloatField(max_length=20, verbose_name='HRU内的总降水')),
                ('PETmm', models.FloatField(max_length=20, verbose_name='长HRU内的潜在蒸散发')),
                ('ETmm', models.FloatField(max_length=20, verbose_name='HRU内的实际蒸散发')),
                ('SW_INITmm', models.FloatField(max_length=20, verbose_name='土壤水含量')),
                ('SW_ENDmm', models.FloatField(max_length=20, verbose_name='土壤水含量最后的土壤剖面的水量')),
                ('PERCmm', models.FloatField(max_length=20, verbose_name='通过根部区域渗漏的水量')),
                ('SA_STmm', models.FloatField(max_length=20, verbose_name='最后的潜水层水储量')),
                ('DA_STmm', models.FloatField(max_length=20, verbose_name='最后的深层含水层水储量')),
                ('TMP_AVdgC', models.FloatField(max_length=20, verbose_name='每日平均气温')),
                ('TMP_MXdgC', models.FloatField(max_length=20, verbose_name='最后的潜水层水储量')),
                ('TMP_MNdgC', models.FloatField(max_length=20, verbose_name='最后的潜水层水储量')),
                ('SOL_TMPdgC', models.FloatField(max_length=20, verbose_name='第一层土壤的平均温度')),
                ('SOLARmj_m2', models.FloatField(max_length=20, verbose_name='每日太阳辐射值')),
                ('YYYYMM', models.CharField(max_length=20, verbose_name='HRU编号')),
            ],
            options={
                'db_table': 'hru_chenxi',
            },
        ),
    ]
