# Generated by Django 3.2.9 on 2022-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WestReservoir', '0002_submodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.SmallIntegerField(verbose_name='代号')),
                ('Count', models.IntegerField(verbose_name='数量')),
                ('Type', models.CharField(max_length=20, verbose_name='土地类别')),
                ('Year', models.IntegerField(default=None, verbose_name='年份')),
            ],
            options={
                'db_table': 'land_type_chenxi',
            },
        ),
    ]
