# Generated by Django 3.2.9 on 2022-01-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WestReservoir', '0003_landtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUB', models.SmallIntegerField(verbose_name='子流域编号')),
                ('YEAR', models.IntegerField(verbose_name='年份')),
                ('MON', models.SmallIntegerField(verbose_name='月份')),
                ('AREAkm2', models.FloatField(max_length=20, verbose_name='河段集水面积')),
                ('FLOW_INcms', models.FloatField(verbose_name='流入河段的平均每日径流')),
                ('FLOW_OUTcms', models.FloatField(verbose_name='流出河段的平均每日径流')),
                ('EVAPcms', models.FloatField(verbose_name='平均每日蒸发损失')),
                ('TLOSScms', models.FloatField(verbose_name='平均每日河床传输损失')),
                ('SED_INtons', models.FloatField(verbose_name='进入河段的泥沙量')),
                ('SED_OUTtons', models.FloatField(verbose_name='流出河段的泥沙量')),
                ('SEDCONCmg_kg', models.FloatField(verbose_name='河段中泥沙浓度')),
                ('ORGN_INkg', models.FloatField(verbose_name='进入河段的有机氮总量')),
                ('ORGN_OUTkg', models.FloatField(verbose_name='流出河段的有机氮总量')),
                ('ORGP_INkg', models.FloatField(verbose_name='进入河段的有机磷总量')),
                ('ORGP_OUTkg', models.FloatField(verbose_name='流出河段的有机磷总量')),
                ('NO3_INkg', models.FloatField(verbose_name='进入河段的硝酸盐总量')),
                ('NO3_OUTkg', models.FloatField(verbose_name='流出河段的硝酸盐总量')),
                ('NH4_INkg', models.FloatField(verbose_name='进入河段的氨氮总量')),
                ('NH4_OUTkg', models.FloatField(verbose_name='流出河段的氨氮总量')),
                ('NO2_INkg', models.FloatField(verbose_name='进入河段的亚硝酸盐总量')),
                ('NO2_OUTkg', models.FloatField(verbose_name='流出河段的亚硝酸盐总量')),
                ('MINP_INkg', models.FloatField(verbose_name='进入河段的矿物质磷总量')),
                ('MINP_OUTkg', models.FloatField(verbose_name='流出河段的矿物质磷总量')),
                ('CHLA_INkg', models.FloatField(verbose_name='叶绿素a被输送到水库的量')),
                ('CHLA_OUTkg', models.FloatField(verbose_name='输送出的叶绿素a量')),
                ('CBOD_INkg', models.FloatField(verbose_name='进入河段的物质的碳质生化需氧量')),
                ('CBOD_OUTkg', models.FloatField(verbose_name='流出河段的物质的碳质生化需氧量')),
                ('DISOX_INkg', models.FloatField(verbose_name='进入河段的溶解氧')),
                ('DISOX_OUTkg', models.FloatField(max_length=20, verbose_name='流出河段的溶解氧')),
                ('YYYYMM', models.CharField(max_length=20, verbose_name='HRU编号')),
            ],
            options={
                'db_table': 'rch_chenxi',
            },
        ),
    ]
