# Generated by Django 3.2.9 on 2022-01-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservoirModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir_name', models.CharField(max_length=50, verbose_name='水库名')),
                ('storage_area', models.IntegerField(max_length=20, verbose_name='蓄水面积')),
                ('water_level', models.FloatField(max_length=20, verbose_name='水位')),
                ('watershed_area', models.IntegerField(max_length=20, verbose_name='流域面积')),
                ('irrigation_area', models.IntegerField(max_length=20, verbose_name='灌溉面积')),
            ],
            options={
                'db_table': 'reservoir',
            },
        ),
    ]
