# Generated by Django 3.2.9 on 2022-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoirmodel',
            name='irrigation_area',
            field=models.IntegerField(verbose_name='灌溉面积'),
        ),
        migrations.AlterField(
            model_name='reservoirmodel',
            name='storage_area',
            field=models.IntegerField(verbose_name='蓄水面积'),
        ),
        migrations.AlterField(
            model_name='reservoirmodel',
            name='watershed_area',
            field=models.IntegerField(verbose_name='流域面积'),
        ),
    ]
