# Generated by Django 3.2.9 on 2022-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_hrumodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrumodel',
            name='MON',
            field=models.IntegerField(verbose_name='月份'),
        ),
    ]
