# Generated by Django 3.2.9 on 2022-01-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_hrumodel_mon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrumodel',
            name='YEAR',
            field=models.IntegerField(default=2000, verbose_name='年份'),
        ),
    ]
