# Generated by Django 3.2.9 on 2022-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_hrumodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUB', models.SmallIntegerField(verbose_name='子流域编号')),
                ('YEAR', models.IntegerField(verbose_name='年份')),
                ('MON', models.SmallIntegerField(verbose_name='月份')),
                ('AREAkm2', models.FloatField(max_length=20, verbose_name='子流域面积')),
                ('PRECIPmm', models.FloatField(verbose_name='子流域内的总降水')),
                ('SNOWMELTmmm', models.FloatField(verbose_name='冰雪融化量')),
                ('PETmm', models.FloatField(verbose_name='子流域内的潜在蒸散发')),
                ('ETmm', models.FloatField(verbose_name='实际蒸散发')),
                ('SWmm', models.FloatField(verbose_name='土壤水含量')),
                ('PERCmm', models.FloatField(verbose_name='通过根部区域渗漏的水量')),
                ('SURQmm', models.FloatField(verbose_name='地表径流对主河道总径流的贡献量')),
                ('GW_Qmm', models.FloatField(verbose_name='地下径流对主河道总径流的贡献量')),
                ('WYLDmm', models.FloatField(verbose_name='子流域进入主河道的总水量')),
                ('SYLDt_ha', models.FloatField(verbose_name='从子流域进入主河道的总泥沙量')),
                ('ORGNkg_ha', models.FloatField(verbose_name='有机氮总量(kgN/ha)')),
                ('ORGPhg_ha', models.FloatField(verbose_name='有机磷总量(kgP/ha)')),
                ('NSURQkg_ha', models.FloatField(verbose_name='随地表径流进入河道的NO3量')),
                ('SOLPkg_ha', models.FloatField(verbose_name='可溶磷总量(kgP/ha)')),
                ('SEDPkg_ha', models.FloatField(verbose_name='随泥沙进入河道的矿物质磷总量')),
            ],
            options={
                'db_table': 'sub_model',
            },
        ),
    ]
