# Generated by Django 3.2.9 on 2022-01-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_submodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submodel',
            table='sub_sha',
        ),
    ]
