# Generated by Django 3.2.9 on 2021-12-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(default=1)),
                ('role', models.CharField(max_length=20, null=True, verbose_name='角色')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='电话')),
                ('status', models.IntegerField(default=0)),
                ('Job', models.CharField(max_length=20, null=True, verbose_name='职务')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='user.user')),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
    ]
